name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libsqlite3-dev
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup database
        run: bin/rails db:test:prepare

      - name: Run tests
        run: bundle exec rspec
